#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>
#include <openssl/evp.h>
#include <openssl/sha.h>
#include <openssl/rand.h>
#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/obj_mac.h>
#include <openssl/crypto.h>

#define VAULT_ITERATIONS 600000
#define SALT_LEN 16
#define IV_LEN 12
#define TAG_LEN 16
#define KEY_LEN 32

static void cleanse(void *p, size_t n){ if(p&&n) OPENSSL_cleanse(p,n); }
static char *xstrndup(const char *s,size_t n){ char *p=malloc(n+1); if(!p) return NULL; memcpy(p,s,n); p[n]=0; return p; }
static char *slurp_stdin(void){ size_t cap=4096,len=0; char *b=malloc(cap); if(!b)return NULL; for(;;){ int c=fgetc(stdin); if(c==EOF){ if(ferror(stdin)){free(b);return NULL;} break; } if(len+2>cap){ cap*=2; char *t=realloc(b,cap); if(!t){free(b);return NULL;} b=t; } b[len++]=(char)c; if(c=='\n') break; } b[len]=0; return b; }
static char *slurp_file(const char *path,size_t *out_len){ FILE *f=fopen(path,"rb"); if(!f)return NULL; fseek(f,0,SEEK_END); long sz=ftell(f); if(sz<0){fclose(f);return NULL;} rewind(f); char *b=malloc((size_t)sz+1); if(!b){fclose(f);return NULL;} size_t n=fread(b,1,(size_t)sz,f); fclose(f); if(n!=(size_t)sz){free(b);return NULL;} b[n]=0; if(out_len)*out_len=n; return b; }
static bool write_file(const char *path,const char *data,size_t len){ FILE *f=fopen(path,"wb"); if(!f)return false; size_t n=fwrite(data,1,len,f); int rc=fclose(f); return n==len && rc==0; }

static char *json_escape(const char *s){ size_t n=strlen(s),cap=n*6+1,j=0; char *o=malloc(cap); if(!o)return NULL; for(size_t i=0;i<n;i++){ unsigned char c=s[i]; switch(c){ case '"':o[j++]='\\';o[j++]='"';break; case '\\':o[j++]='\\';o[j++]='\\';break; case '\n':o[j++]='\\';o[j++]='n';break; case '\r':o[j++]='\\';o[j++]='r';break; case '\t':o[j++]='\\';o[j++]='t';break; case '\b':o[j++]='\\';o[j++]='b';break; case '\f':o[j++]='\\';o[j++]='f';break; default: if(c<32){snprintf(o+j,cap-j,"\\u%04x",c); j+=6;} else o[j++]=(char)c; }} o[j]=0; return o; }
static void ok_obj(const char *obj){ printf("{\"ok\":true,\"result\":%s}\n",obj?obj:"{}"); }
static void err_msg(const char *m){ char *e=json_escape(m?m:"error"); printf("{\"ok\":false,\"error\":\"%s\"}\n",e?e:"oom"); free(e); }

static int hx(char c){ if(c>='0'&&c<='9')return c-'0'; if(c>='a'&&c<='f')return c-'a'+10; if(c>='A'&&c<='F')return c-'A'+10; return -1; }
static bool hex_decode(const char *h,uint8_t *out,size_t n){ if(!h||strlen(h)!=2*n)return false; for(size_t i=0;i<n;i++){int a=hx(h[2*i]),b=hx(h[2*i+1]); if(a<0||b<0)return false; out[i]=(uint8_t)((a<<4)|b);} return true; }
static char *hex_encode(const uint8_t *d,size_t n){ static const char *hh="0123456789abcdef"; char *o=malloc(n*2+1); if(!o)return NULL; for(size_t i=0;i<n;i++){o[2*i]=hh[d[i]>>4]; o[2*i+1]=hh[d[i]&15];} o[2*n]=0; return o; }
static bool hex64(const char *s){ if(!s||strlen(s)!=64)return false; for(int i=0;i<64;i++) if(!isxdigit((unsigned char)s[i])) return false; return true; }

static const char *find_key(const char *json,const char *key){ char pat[128]; snprintf(pat,sizeof(pat),"\"%s\"",key); const char *p=json; while((p=strstr(p,pat))){ p+=strlen(pat); while(*p&&isspace((unsigned char)*p))p++; if(*p==':') return p+1; } return NULL; }
static const char *skip_ws(const char *p){ while(p&&*p&&isspace((unsigned char)*p))p++; return p; }
static char *json_unescape_slice(const char *s,size_t n){ char *o=malloc(n+1); if(!o)return NULL; size_t j=0; for(size_t i=0;i<n;i++){ char c=s[i]; if(c!='\\'){o[j++]=c;continue;} if(++i>=n){free(o);return NULL;} c=s[i]; switch(c){ case '"':o[j++]='"';break; case '\\':o[j++]='\\';break; case '/':o[j++]='/';break; case 'b':o[j++]='\b';break; case 'f':o[j++]='\f';break; case 'n':o[j++]='\n';break; case 'r':o[j++]='\r';break; case 't':o[j++]='\t';break; case 'u': if(i+4<n){ o[j++]='?'; i+=4; } else {free(o);return NULL;} break; default: free(o);return NULL; }} o[j]=0; return o; }
static char *json_get_string(const char *json,const char *key){ const char *p=skip_ws(find_key(json,key)); if(!p||*p!='"')return NULL; p++; const char *start=p; bool esc=false; while(*p){ if(esc){esc=false; p++; continue;} if(*p=='\\'){esc=true; p++; continue;} if(*p=='"') return json_unescape_slice(start,(size_t)(p-start)); p++; } return NULL; }
static char *json_get_raw_value(const char *json,const char *key){ const char *p=skip_ws(find_key(json,key)); if(!p)return NULL; const char *s=p; if(*p=='"'){ p++; bool esc=false; while(*p){ if(esc){esc=false;p++;continue;} if(*p=='\\'){esc=true;p++;continue;} if(*p=='"'){p++; return xstrndup(s,(size_t)(p-s));} p++; } return NULL; } if(*p=='{'||*p=='['){ char open=*p, close=(*p=='{'?'}':']'); int depth=0; bool instr=false,esc=false; while(*p){ char c=*p; if(instr){ if(esc)esc=false; else if(c=='\\')esc=true; else if(c=='"')instr=false; p++; continue; } if(c=='"'){instr=true;p++;continue;} if(c==open)depth++; if(c==close){depth--; if(depth==0){p++; return xstrndup(s,(size_t)(p-s));}} p++; } return NULL; } while(*p && *p!=',' && *p!='}' && *p!=']' && !isspace((unsigned char)*p))p++; return xstrndup(s,(size_t)(p-s)); }
static char *json_get_object(const char *json,const char *key){ char *v=json_get_raw_value(json,key); if(!v||v[0]!='{'){free(v);return NULL;} return v; }

static void sha256_bytes(const uint8_t *d,size_t n,uint8_t out[32]){ unsigned int l=0; EVP_Digest(d,n,out,&l,EVP_sha256(),NULL); }

/* bech32 npub */
static const char *B32="qpzry9x8gf2tvdw0s3jn54khce6mua7l";
static uint32_t polymod(const uint8_t *v,size_t n){ uint32_t chk=1; static const uint32_t g[5]={0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3}; for(size_t i=0;i<n;i++){uint8_t top=chk>>25; chk=(chk&0x1ffffff)<<5 ^ v[i]; for(int j=0;j<5;j++) if((top>>j)&1) chk^=g[j];} return chk; }
static size_t hrp_expand(uint8_t *o){ const char *h="npub"; size_t j=0; for(size_t i=0;i<4;i++)o[j++]=h[i]>>5; o[j++]=0; for(size_t i=0;i<4;i++)o[j++]=h[i]&31; return j; }
static size_t conv8to5(const uint8_t *in,size_t n,uint8_t *out){ uint32_t acc=0; int bits=0; size_t j=0; for(size_t i=0;i<n;i++){acc=(acc<<8)|in[i]; bits+=8; while(bits>=5){bits-=5; out[j++]=(acc>>bits)&31;}} if(bits>0)out[j++]=(acc<<(5-bits))&31; return j; }
static char *npub_encode(const uint8_t pub[32]){ uint8_t data[64],vals[128],cs[6]; size_t dl=conv8to5(pub,32,data), vl=hrp_expand(vals); memcpy(vals+vl,data,dl); vl+=dl; memset(vals+vl,0,6); uint32_t m=polymod(vals,vl+6)^1; for(int i=0;i<6;i++)cs[i]=(m>>(5*(5-i)))&31; char *o=malloc(5+dl+6+1); if(!o)return NULL; memcpy(o,"npub1",5); size_t j=5; for(size_t i=0;i<dl;i++)o[j++]=B32[data[i]]; for(int i=0;i<6;i++)o[j++]=B32[cs[i]]; o[j]=0; return o; }

/* secp256k1 + BIP340 */
static EC_GROUP *group_new(void){ EC_GROUP *g=EC_GROUP_new_by_curve_name(NID_secp256k1); if(g)EC_GROUP_set_asn1_flag(g,OPENSSL_EC_NAMED_CURVE); return g; }
static bool bn32(const BIGNUM *b,uint8_t out[32]){ return BN_bn2binpad(b,out,32)==32; }
static bool scalar_ok(const BIGNUM *d,const BIGNUM *n){ return !BN_is_zero(d)&&!BN_is_negative(d)&&BN_cmp(d,n)<0; }
static bool pub_from_priv(const uint8_t priv[32],uint8_t pub[32],bool *odd){ bool ok=false; BN_CTX *ctx=BN_CTX_new(); EC_GROUP *g=group_new(); EC_POINT *P=NULL; BIGNUM *d=NULL,*x=NULL,*y=NULL,*n=NULL; if(!ctx||!g)goto done; P=EC_POINT_new(g); d=BN_bin2bn(priv,32,NULL); x=BN_new(); y=BN_new(); n=BN_new(); if(!P||!d||!x||!y||!n)goto done; if(!EC_GROUP_get_order(g,n,ctx)||!scalar_ok(d,n))goto done; if(!EC_POINT_mul(g,P,d,NULL,NULL,ctx))goto done; if(!EC_POINT_get_affine_coordinates(g,P,x,y,ctx))goto done; if(!bn32(x,pub))goto done; if(odd)*odd=BN_is_odd(y); ok=true; done: BN_clear_free(d); BN_free(x); BN_free(y); BN_free(n); EC_POINT_free(P); EC_GROUP_free(g); BN_CTX_free(ctx); return ok; }
static bool keygen(uint8_t priv[32],uint8_t pub[32]){ bool ok=false; BN_CTX *ctx=BN_CTX_new(); EC_GROUP *g=group_new(); BIGNUM *d=BN_new(),*n=BN_new(),*adj=BN_new(); if(!ctx||!g||!d||!n||!adj)goto done; if(!EC_GROUP_get_order(g,n,ctx))goto done; for(int i=0;i<1024;i++){ if(RAND_bytes(priv,32)!=1)goto done; BN_bin2bn(priv,32,d); if(!scalar_ok(d,n))continue; bool odd=false; if(!pub_from_priv(priv,pub,&odd))continue; if(odd){ if(!BN_sub(adj,n,d)||!bn32(adj,priv))goto done; if(!pub_from_priv(priv,pub,&odd)||odd)goto done; } ok=true; break; } done: BN_clear_free(d); BN_free(n); BN_clear_free(adj); EC_GROUP_free(g); BN_CTX_free(ctx); return ok; }
static void tagged(const char *tag,const uint8_t *m,size_t ml,uint8_t out[32]){ uint8_t th[32]; unsigned int l=0; sha256_bytes((const uint8_t*)tag,strlen(tag),th); EVP_MD_CTX *c=EVP_MD_CTX_new(); if(!c){memset(out,0,32);return;} EVP_DigestInit_ex(c,EVP_sha256(),NULL); EVP_DigestUpdate(c,th,32); EVP_DigestUpdate(c,th,32); EVP_DigestUpdate(c,m,ml); EVP_DigestFinal_ex(c,out,&l); EVP_MD_CTX_free(c); }
static bool schnorr_sign(const uint8_t priv[32],const uint8_t msg[32],uint8_t sig[64]){ bool ok=false,odd=false; uint8_t pk[32],aux[32],ah[32],t[32],nin[96],rand[32],rx[32],cin[96],ebytes[32]; if(!pub_from_priv(priv,pk,&odd)||odd)return false; if(RAND_bytes(aux,32)!=1)return false; tagged("BIP0340/aux",aux,32,ah); for(int i=0;i<32;i++)t[i]=priv[i]^ah[i]; memcpy(nin,t,32);memcpy(nin+32,pk,32);memcpy(nin+64,msg,32); tagged("BIP0340/nonce",nin,96,rand); BN_CTX *ctx=BN_CTX_new(); EC_GROUP *g=group_new(); EC_POINT *R=NULL; BIGNUM *n=NULL,*d=NULL,*k0=NULL,*k=NULL,*x=NULL,*y=NULL,*e=NULL,*ed=NULL,*s=NULL; if(!ctx||!g)goto done; R=EC_POINT_new(g); n=BN_new(); d=BN_bin2bn(priv,32,NULL); k0=BN_bin2bn(rand,32,NULL); k=BN_new(); x=BN_new(); y=BN_new(); e=BN_new(); ed=BN_new(); s=BN_new(); if(!R||!n||!d||!k0||!k||!x||!y||!e||!ed||!s)goto done; if(!EC_GROUP_get_order(g,n,ctx))goto done; BN_mod(k0,k0,n,ctx); if(BN_is_zero(k0))goto done; if(!EC_POINT_mul(g,R,k0,NULL,NULL,ctx))goto done; if(!EC_POINT_get_affine_coordinates(g,R,x,y,ctx))goto done; if(BN_is_odd(y)){ if(!BN_sub(k,n,k0))goto done; } else if(!BN_copy(k,k0))goto done; if(!bn32(x,rx))goto done; memcpy(cin,rx,32);memcpy(cin+32,pk,32);memcpy(cin+64,msg,32); tagged("BIP0340/challenge",cin,96,ebytes); BN_bin2bn(ebytes,32,e); BN_mod(e,e,n,ctx); if(!BN_mod_mul(ed,e,d,n,ctx))goto done; if(!BN_mod_add(s,k,ed,n,ctx))goto done; memcpy(sig,rx,32); if(!bn32(s,sig+32))goto done; ok=true; done: cleanse(aux,32);cleanse(ah,32);cleanse(t,32);cleanse(nin,96);cleanse(rand,32); BN_free(n);BN_clear_free(d);BN_clear_free(k0);BN_clear_free(k);BN_free(x);BN_free(y);BN_free(e);BN_clear_free(ed);BN_clear_free(s);EC_POINT_free(R);EC_GROUP_free(g);BN_CTX_free(ctx); return ok; }

/* vault */
struct vault { uint8_t priv[32]; char pub[65]; char npub[128]; };
static const char *passphrase(void){ const char *p=getenv("DAMAGE_NSECBUNKER_VAULT_PASSPHRASE"); return (p&&*p)?p:NULL; }
static bool derive(const char *pass,const uint8_t salt[SALT_LEN],uint8_t key[KEY_LEN]){ return PKCS5_PBKDF2_HMAC(pass,(int)strlen(pass),salt,SALT_LEN,VAULT_ITERATIONS,EVP_sha256(),KEY_LEN,key)==1; }
static bool gcm_enc(const uint8_t key[32],const uint8_t iv[12],const uint8_t *pt,int pl,uint8_t **ct,int *cl,uint8_t tag[16]){ EVP_CIPHER_CTX *c=EVP_CIPHER_CTX_new(); if(!c)return false; bool ok=false; int l=0; *ct=malloc((size_t)pl+16); if(!*ct)goto done; if(EVP_EncryptInit_ex(c,EVP_aes_256_gcm(),NULL,NULL,NULL)!=1)goto done; if(EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_IVLEN,12,NULL)!=1)goto done; if(EVP_EncryptInit_ex(c,NULL,NULL,key,iv)!=1)goto done; if(EVP_EncryptUpdate(c,*ct,&l,pt,pl)!=1)goto done; *cl=l; if(EVP_EncryptFinal_ex(c,*ct+*cl,&l)!=1)goto done; *cl+=l; if(EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_GET_TAG,16,tag)!=1)goto done; ok=true; done: if(!ok&&*ct){free(*ct);*ct=NULL;} EVP_CIPHER_CTX_free(c); return ok; }
static bool gcm_dec(const uint8_t key[32],const uint8_t iv[12],const uint8_t *ct,int cl,const uint8_t tag[16],uint8_t **pt,int *pl){ EVP_CIPHER_CTX *c=EVP_CIPHER_CTX_new(); if(!c)return false; bool ok=false; int l=0; *pt=malloc((size_t)cl+1); if(!*pt)goto done; if(EVP_DecryptInit_ex(c,EVP_aes_256_gcm(),NULL,NULL,NULL)!=1)goto done; if(EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_IVLEN,12,NULL)!=1)goto done; if(EVP_DecryptInit_ex(c,NULL,NULL,key,iv)!=1)goto done; if(EVP_DecryptUpdate(c,*pt,&l,ct,cl)!=1)goto done; *pl=l; if(EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_TAG,16,(void*)tag)!=1)goto done; if(EVP_DecryptFinal_ex(c,*pt+*pl,&l)!=1)goto done; *pl+=l; (*pt)[*pl]=0; ok=true; done: if(!ok&&*pt){free(*pt);*pt=NULL;} EVP_CIPHER_CTX_free(c); return ok; }
static bool save_vault(const char *path,struct vault *v){ const char *pass=passphrase(); if(!pass){err_msg("missing_DAMAGE_NSECBUNKER_VAULT_PASSPHRASE");return false;} char *priv=hex_encode(v->priv,32); if(!priv)return false; char plain[512]; snprintf(plain,sizeof(plain),"{\"privkey_hex\":\"%s\",\"pubkey_hex\":\"%s\",\"npub\":\"%s\"}",priv,v->pub,v->npub); cleanse(priv,strlen(priv)); free(priv); uint8_t salt[SALT_LEN],iv[IV_LEN],key[KEY_LEN],tag[TAG_LEN],*ct=NULL; int cl=0; if(RAND_bytes(salt,SALT_LEN)!=1||RAND_bytes(iv,IV_LEN)!=1){err_msg("vault_random_failed");return false;} if(!derive(pass,salt,key)){err_msg("vault_kdf_failed");return false;} if(!gcm_enc(key,iv,(uint8_t*)plain,(int)strlen(plain),&ct,&cl,tag)){err_msg("vault_encrypt_failed");return false;} char *sh=hex_encode(salt,SALT_LEN),*ih=hex_encode(iv,IV_LEN),*th=hex_encode(tag,TAG_LEN),*ch=hex_encode(ct,(size_t)cl); size_t cap=strlen(ch)+512; char *out=malloc(cap); snprintf(out,cap,"{\"v\":1,\"backend\":\"damage-nsecbunker-crypto-c\",\"kdf\":\"pbkdf2-hmac-sha256\",\"iterations\":%d,\"cipher\":\"aes-256-gcm\",\"salt\":\"%s\",\"iv\":\"%s\",\"tag\":\"%s\",\"ciphertext\":\"%s\"}\n",VAULT_ITERATIONS,sh,ih,th,ch); bool ok=write_file(path,out,strlen(out)); if(!ok)err_msg("vault_write_failed"); cleanse(key,KEY_LEN); cleanse(plain,strlen(plain)); cleanse(ct,(size_t)cl); free(ct); free(sh);free(ih);free(th);free(ch);free(out); return ok; }
static bool load_vault(const char *path,struct vault *v){ memset(v,0,sizeof(*v)); const char *pass=passphrase(); if(!pass){err_msg("missing_DAMAGE_NSECBUNKER_VAULT_PASSPHRASE");return false;} char *file=slurp_file(path,NULL); if(!file){err_msg("vault_read_failed");return false;} char *sh=json_get_string(file,"salt"),*ih=json_get_string(file,"iv"),*th=json_get_string(file,"tag"),*ch=json_get_string(file,"ciphertext"); if(!sh||!ih||!th||!ch){err_msg("vault_missing_fields"); goto fail;} size_t cl=strlen(ch)/2; uint8_t salt[SALT_LEN],iv[IV_LEN],tag[TAG_LEN],key[KEY_LEN],*ct=malloc(cl),*pt=NULL; int pl=0; if(!ct){err_msg("oom");goto fail;} if(!hex_decode(sh,salt,SALT_LEN)||!hex_decode(ih,iv,IV_LEN)||!hex_decode(th,tag,TAG_LEN)||!hex_decode(ch,ct,cl)){err_msg("vault_hex_decode_failed");goto fail2;} if(!derive(pass,salt,key)){err_msg("vault_kdf_failed");goto fail2;} if(!gcm_dec(key,iv,ct,(int)cl,tag,&pt,&pl)){err_msg("vault_decrypt_failed");goto fail2;} char *priv=json_get_string((char*)pt,"privkey_hex"),*pub=json_get_string((char*)pt,"pubkey_hex"),*np=json_get_string((char*)pt,"npub"); if(!priv||!pub||!np||!hex64(priv)||!hex64(pub)){err_msg("vault_plaintext_invalid"); free(priv);free(pub);free(np); goto fail3;} hex_decode(priv,v->priv,32); snprintf(v->pub,sizeof(v->pub),"%s",pub); snprintf(v->npub,sizeof(v->npub),"%s",np); cleanse(priv,strlen(priv)); free(priv);free(pub);free(np); cleanse(pt,(size_t)pl); free(pt); cleanse(key,KEY_LEN); cleanse(ct,cl); free(ct); free(sh);free(ih);free(th);free(ch);free(file); return true; fail3: if(pt){cleanse(pt,(size_t)pl);free(pt);} fail2: cleanse(key,KEY_LEN); if(ct){cleanse(ct,cl);free(ct);} fail: free(sh);free(ih);free(th);free(ch);free(file); return false; }

static char *vault_path(char *json){ char *p=json_get_string(json,"vault_path"); if(p)return p; const char *e=getenv("DAMAGE_NSECBUNKER_VAULT_PATH"); return (e&&*e)?xstrndup(e,strlen(e)):NULL; }
static bool op_health(void){ ok_obj("{\"protocol\":\"damage-nsecbunker-crypto-v1\",\"backend\":\"damage-nsecbunker-crypto-c\",\"phase\":\"2b\",\"crypto\":\"openssl-secp256k1-bip340\",\"mode\":\"openssl_secp256k1_bip340_phase2b\",\"nip44\":\"plain-loopback-only\"}"); return true; }
static bool op_generate(char *json){ char *path=vault_path(json); if(!path){err_msg("missing_vault_path");return false;} struct vault v; uint8_t pub[32]; if(!keygen(v.priv,pub)){free(path);err_msg("key_generation_failed");return false;} char *ph=hex_encode(pub,32),*np=npub_encode(pub); snprintf(v.pub,sizeof(v.pub),"%s",ph); snprintf(v.npub,sizeof(v.npub),"%s",np); bool ok=save_vault(path,&v); if(ok)printf("{\"ok\":true,\"result\":{\"pubkey_hex\":\"%s\",\"npub\":\"%s\",\"vault_written\":true}}\n",ph,np); cleanse(&v,sizeof(v)); free(path);free(ph);free(np); return ok; }
static bool op_public(char *json){ char *path=vault_path(json); if(!path){err_msg("missing_vault_path");return false;} struct vault v; bool ok=load_vault(path,&v); if(ok)printf("{\"ok\":true,\"result\":{\"pubkey_hex\":\"%s\",\"npub\":\"%s\"}}\n",v.pub,v.npub); cleanse(&v,sizeof(v)); free(path); return ok; }
static bool op_npub(char *json){ char *p=json_get_string(json,"pubkey_hex"); if(!hex64(p)){free(p);err_msg("invalid_pubkey_hex");return false;} uint8_t pub[32]; hex_decode(p,pub,32); char *np=npub_encode(pub); printf("{\"ok\":true,\"result\":{\"npub\":\"%s\"}}\n",np); free(p);free(np); return true; }
static bool op_sign(char *json){ char *path=vault_path(json); char *event=json_get_object(json,"event"); if(!path||!event){free(path);free(event);err_msg("missing_vault_path_or_event");return false;} struct vault v; if(!load_vault(path,&v)){free(path);free(event);return false;} char *ep=json_get_string(event,"pubkey"); if(ep&&*ep&&strcmp(ep,v.pub)!=0){free(ep);free(path);free(event);cleanse(&v,sizeof(v));err_msg("event_pubkey_mismatch");return false;} free(ep); char *created=json_get_raw_value(event,"created_at"),*kind=json_get_raw_value(event,"kind"),*tags=json_get_raw_value(event,"tags"),*content=json_get_raw_value(event,"content"); if(!created||!kind||!content){err_msg("event_missing_required_fields");free(path);free(event);free(created);free(kind);free(tags);free(content);cleanse(&v,sizeof(v));return false;} if(!tags)tags=xstrndup("[]",2); size_t sl=strlen(v.pub)+strlen(created)+strlen(kind)+strlen(tags)+strlen(content)+64; char *ser=malloc(sl); snprintf(ser,sl,"[0,\"%s\",%s,%s,%s,%s]",v.pub,created,kind,tags,content); uint8_t id[32],sig[64]; sha256_bytes((uint8_t*)ser,strlen(ser),id); if(!schnorr_sign(v.priv,id,sig)){err_msg("schnorr_sign_failed");free(path);free(event);free(created);free(kind);free(tags);free(content);free(ser);cleanse(&v,sizeof(v));return false;} char *idh=hex_encode(id,32),*sigh=hex_encode(sig,64); printf("{\"ok\":true,\"result\":{\"event\":{\"id\":\"%s\",\"pubkey\":\"%s\",\"created_at\":%s,\"kind\":%s,\"tags\":%s,\"content\":%s,\"sig\":\"%s\"}}}\n",idh,v.pub,created,kind,tags,content,sigh); cleanse(sig,64); free(idh);free(sigh);free(path);free(event);free(created);free(kind);free(tags);free(content);free(ser);cleanse(&v,sizeof(v));return true; }
static char *b64e(const uint8_t *d,size_t n){ size_t cap=4*((n+2)/3)+1; char *o=malloc(cap); int l=EVP_EncodeBlock((unsigned char*)o,d,(int)n); o[l]=0; return o; }
static uint8_t *b64d(const char *s,size_t *out){ size_t n=strlen(s); uint8_t *o=malloc(n+1); int l=EVP_DecodeBlock(o,(const unsigned char*)s,(int)n); if(l<0){free(o);return NULL;} while(n>0&&s[n-1]=='='){l--;n--;} *out=(size_t)l; return o; }
static bool plain_allowed(void){ const char *v=getenv("DAMAGE_NSECBUNKER_ALLOW_PLAIN_NIP44"); return v&&strcmp(v,"1")==0; }
static bool op_encrypt(char *json){ if(!plain_allowed()){err_msg("nip44_not_implemented_in_phase2b_without_plain_loopback");return false;} char *p=json_get_string(json,"plaintext"); if(!p){err_msg("missing_plaintext");return false;} char *b=b64e((uint8_t*)p,strlen(p)); printf("{\"ok\":true,\"result\":{\"ciphertext\":\"plain:%s\"}}\n",b); cleanse(p,strlen(p)); free(p);free(b);return true; }
static bool op_decrypt(char *json){ if(!plain_allowed()){err_msg("nip44_not_implemented_in_phase2b_without_plain_loopback");return false;} char *c=json_get_string(json,"ciphertext"); if(!c||strncmp(c,"plain:",6)!=0){free(c);err_msg("phase2b_plain_ciphertext_required");return false;} size_t n=0; uint8_t *p=b64d(c+6,&n); if(!p){free(c);err_msg("base64_decode_failed");return false;} char *tmp=xstrndup((char*)p,n),*esc=json_escape(tmp); printf("{\"ok\":true,\"result\":{\"plaintext\":\"%s\"}}\n",esc); cleanse(p,n);free(p);cleanse(tmp,n);free(tmp);free(esc);free(c);return true; }

int main(void){ char *json=slurp_stdin(); if(!json){err_msg("stdin_read_failed");return 1;} char *op=json_get_string(json,"op"); if(!op){err_msg("missing_op");free(json);return 1;} bool ok=false; if(strcmp(op,"health")==0)ok=op_health(); else if(strcmp(op,"generate_identity")==0)ok=op_generate(json); else if(strcmp(op,"get_public_key")==0)ok=op_public(json); else if(strcmp(op,"npub")==0)ok=op_npub(json); else if(strcmp(op,"sign_event")==0)ok=op_sign(json); else if(strcmp(op,"nip44_encrypt")==0)ok=op_encrypt(json); else if(strcmp(op,"nip44_decrypt")==0)ok=op_decrypt(json); else {err_msg("unsupported_op"); ok=false;} free(op); free(json); return ok?0:2; }
