sync:
    port: 3015
    log_peer_connection_count_interval: 6000000

http:
    external:
        port: 3013
    internal:
        port: 3113
    endpoints:
        dry-run: true

websocket:
    channel:
        port: 3014

chain:
    persist: true
    garbage_collection:
        enabled: true
        interval: 3
        history: 500

fork_management:
    network_id: ae_uat

logging:
  level: warning

