version: '3.1'
services:
  ae_mdw:
    image: aeternity/ae_mdw:latest
    ports:
      - "0.0.0.0:4000:4000" #MDW's default port
      - "0.0.0.0:4002:4001" #MDW's websocket default port
      - "0.0.0.0:3113:3113" #Node's default internal API port
      - "0.0.0.0:3013:3013" #Node's default external API port
      - "0.0.0.0:3014:3014" #Node's channels default websocket port
    volumes:
      #- ${PWD}/data/mnesia:/home/aeternity/node/local/rel/aeternity/data/mnesia
      #- ${PWD}/data/mdw.db:/home/aeternity/node/local/rel/aeternity/data/mdw.db
      #- ${PWD}/log:/home/aeternity/node/ae_mdw/log
      - ${PWD}/aeternity.testnet.yaml:/home/aeternity/aeternity.yaml
      - ${HOME}/.aeternity/testdb/:/home/aeternity/node/local/rel/aeternity/data/mnesia
      - ${HOME}/.aeternity/testdb.mdw.db/:/home/aeternity/node/local/rel/aeternity/data/mdw.db
      # uncomment for custom node setup
      #- ${HOME}/aeternity.yaml:/home/aeternity/aeternity.yaml
    environment:
      - AETERNITY_CONFIG=/home/aeternity/aeternity.yaml
      - DISABLE_IPV6=true
