%%--------------------------------------------------------------------
%% Cowboy handler for the OTP-managed Wikimedia fixture service.
%%
%% Only GET and HEAD are accepted. File access is restricted to exact route
%% entries generated by ecai_wikimedia_fixture_server, so no caller-controlled
%% filesystem path is ever opened. Single byte ranges and validators are
%% supported to exercise the same resumable downloader used for live dumps.
%%--------------------------------------------------------------------
-module(ecai_wikimedia_fixture_handler).

-export([init/2, parse_range/2, content_type/1]).

-spec init(cowboy_req:req(), map()) -> {ok, cowboy_req:req(), map()}.
init(Req0, #{action := health, server := Server} = State) ->
    serve_status(Req0, Server, State, health);
init(Req0, #{action := status, server := Server} = State) ->
    serve_status(Req0, Server, State, status);
init(Req0, #{action := file, entry := Entry} = State) ->
    serve_entry(Req0, Entry, State);
init(Req0, State) ->
    reply_json(Req0, 404, #{ok => false, error => not_found}, State).

serve_status(Req0, Server, State, Kind) ->
    case allowed_method(cowboy_req:method(Req0)) of
        {ok, HeadOnly} ->
            try ecai_wikimedia_fixture_server:status(Server) of
                Status when is_map(Status) ->
                    Body =
                        case Kind of
                            health -> maps:merge(#{ok => true}, Status);
                            status -> #{ok => true, status => Status}
                        end,
                    reply_json(Req0, 200, Body, State, HeadOnly);
                Other ->
                    reply_json(
                        Req0,
                        503,
                        #{ok => false, ready => false, error => {invalid_status, Other}},
                        State,
                        HeadOnly
                    )
            catch
                Class:Reason ->
                    reply_json(
                        Req0,
                        503,
                        #{
                            ok => false,
                            ready => false,
                            error => {fixture_server_unavailable, Class, Reason}
                        },
                        State,
                        HeadOnly
                    )
            end;
        error ->
            method_not_allowed(Req0, State)
    end.

serve_entry(Req0, Entry, State) ->
    case allowed_method(cowboy_req:method(Req0)) of
        {ok, HeadOnly} ->
            serve_file(Req0, Entry, HeadOnly, State);
        error ->
            method_not_allowed(Req0, State)
    end.

allowed_method(<<"GET">>) -> {ok, false};
allowed_method(<<"HEAD">>) -> {ok, true};
allowed_method(_) -> error.

serve_file(Req0, Entry, HeadOnly, State) ->
    Etag = maps:get(etag, Entry),
    IfNoneMatch = cowboy_req:header(<<"if-none-match">>, Req0, undefined),
    case etag_matches(IfNoneMatch, Etag) of
        true ->
            Headers = common_headers(#{
                <<"etag">> => Etag,
                <<"cache-control">> => <<"no-cache">>
            }),
            Req1 = cowboy_req:reply(304, Headers, <<>>, Req0),
            {ok, Req1, State};
        false ->
            serve_file_range(Req0, Entry, HeadOnly, State)
    end.

serve_file_range(Req0, Entry, HeadOnly, State) ->
    Size = maps:get(size, Entry),
    Etag = maps:get(etag, Entry),
    RangeHeader = cowboy_req:header(<<"range">>, Req0, undefined),
    IfRange = cowboy_req:header(<<"if-range">>, Req0, undefined),
    HonorRange =
        case {RangeHeader, IfRange} of
            {undefined, _} -> false;
            {_Range, undefined} -> true;
            {_Range, Etag} -> true;
            {_Range, _OtherValidator} -> false
        end,
    case HonorRange of
        false ->
            reply_file(Req0, Entry, 200, 0, Size, undefined, HeadOnly, State);
        true ->
            case parse_range(RangeHeader, Size) of
                {ok, Offset, Length} ->
                    End = Offset + Length - 1,
                    ContentRange = iolist_to_binary(
                        io_lib:format("bytes ~B-~B/~B", [Offset, End, Size])
                    ),
                    reply_file(
                        Req0,
                        Entry,
                        206,
                        Offset,
                        Length,
                        ContentRange,
                        HeadOnly,
                        State
                    );
                {error, _Reason} ->
                    Headers = common_headers(#{
                        <<"accept-ranges">> => <<"bytes">>,
                        <<"content-range">> => iolist_to_binary(
                            io_lib:format("bytes */~B", [Size])
                        ),
                        <<"content-length">> => <<"0">>,
                        <<"etag">> => Etag
                    }),
                    Req1 = cowboy_req:reply(416, Headers, <<>>, Req0),
                    {ok, Req1, State}
            end
    end.

reply_file(
    Req0,
    Entry,
    Status,
    Offset,
    Length,
    ContentRange,
    _HeadOnly,
    State
) ->
    Headers0 = #{
        <<"accept-ranges">> => <<"bytes">>,
        <<"cache-control">> => <<"no-cache">>,
        <<"content-type">> => maps:get(content_type, Entry),
        <<"content-length">> => integer_to_binary(Length),
        <<"etag">> => maps:get(etag, Entry)
    },
    Headers1 =
        case ContentRange of
            undefined -> Headers0;
            Value -> Headers0#{<<"content-range">> => Value}
        end,
    Headers = common_headers(Headers1),
    Body =
        case Length of
            0 -> <<>>;
            _ -> {sendfile, Offset, Length, maps:get(path, Entry)}
        end,
    %% Give Cowboy the actual representation for both GET and HEAD. Cowboy
    %% suppresses the payload for HEAD based on the request method while
    %% retaining the representation Content-Length. reply/3 has no response
    %% body and therefore normalizes Content-Length to zero.
    Req1 = cowboy_req:reply(Status, Headers, Body, Req0),
    {ok, Req1, State}.

method_not_allowed(Req0, State) ->
    reply_json(
        Req0,
        405,
        #{ok => false, error => method_not_allowed},
        State,
        false,
        #{<<"allow">> => <<"GET, HEAD">>}
    ).

reply_json(Req0, Code, Body, State) ->
    reply_json(Req0, Code, Body, State, false).

reply_json(Req0, Code, Body0, State, HeadOnly) ->
    reply_json(Req0, Code, Body0, State, HeadOnly, #{}).

reply_json(Req0, Code, Body0, State, _HeadOnly, ExtraHeaders) ->
    Body = jsx:encode(externalize(Body0)),
    Headers = common_headers(
        maps:merge(
            #{
                <<"content-type">> => <<"application/json; charset=utf-8">>,
                <<"content-length">> => integer_to_binary(byte_size(Body)),
                <<"cache-control">> => <<"no-store">>
            },
            ExtraHeaders
        )
    ),
    %% The same rule applies to JSON: pass the representation to reply/4 and
    %% let Cowboy implement HEAD semantics. This preserves the GET-equivalent
    %% Content-Length without transmitting the body.
    Req1 = cowboy_req:reply(Code, Headers, Body, Req0),
    {ok, Req1, State}.

common_headers(Headers) ->
    Headers#{
        <<"x-content-type-options">> => <<"nosniff">>,
        <<"x-ecai-fixture-server">> => <<"managed-otp">>
    }.

etag_matches(undefined, _Etag) ->
    false;
etag_matches(<<"*">>, _Etag) ->
    true;
etag_matches(Header, Etag) when is_binary(Header), is_binary(Etag) ->
    lists:any(
        fun(Candidate) -> trim_ascii_space(Candidate) =:= Etag end,
        binary:split(Header, <<",">>, [global])
    );
etag_matches(_Header, _Etag) ->
    false.

trim_ascii_space(Bin) when is_binary(Bin) ->
    trim_ascii_space_left(trim_ascii_space_right(Bin)).

trim_ascii_space_left(<<Byte, Rest/binary>>) when Byte =:= 32; Byte =:= 9 ->
    trim_ascii_space_left(Rest);
trim_ascii_space_left(Bin) ->
    Bin.

trim_ascii_space_right(Bin) ->
    trim_ascii_space_right(Bin, byte_size(Bin)).

trim_ascii_space_right(_Bin, 0) ->
    <<>>;
trim_ascii_space_right(Bin, Size) ->
    case binary:at(Bin, Size - 1) of
        Byte when Byte =:= 32; Byte =:= 9 ->
            trim_ascii_space_right(Bin, Size - 1);
        _ ->
            binary:part(Bin, 0, Size)
    end.

-spec parse_range(binary(), non_neg_integer()) ->
    {ok, non_neg_integer(), pos_integer()} | {error, term()}.
parse_range(_Header, 0) ->
    {error, unsatisfiable};
parse_range(<<"bytes=", Spec/binary>>, Size) when is_integer(Size), Size > 0 ->
    case binary:match(Spec, <<",">>) of
        nomatch -> parse_single_range(Spec, Size);
        _ -> {error, multiple_ranges_unsupported}
    end;
parse_range(_Header, _Size) ->
    {error, invalid_range_unit}.

parse_single_range(Spec, Size) ->
    case binary:split(Spec, <<"-">>, [global]) of
        [<<>>, SuffixBin] ->
            case parse_nonnegative_integer(SuffixBin) of
                {ok, 0} ->
                    {error, invalid_suffix_length};
                {ok, SuffixLength} ->
                    Length = erlang:min(SuffixLength, Size),
                    {ok, Size - Length, Length};
                error ->
                    {error, invalid_suffix_length}
            end;
        [StartBin, <<>>] ->
            case parse_nonnegative_integer(StartBin) of
                {ok, Start} when Start < Size ->
                    {ok, Start, Size - Start};
                {ok, _Start} ->
                    {error, unsatisfiable};
                error ->
                    {error, invalid_start}
            end;
        [StartBin, EndBin] ->
            case
                {
                    parse_nonnegative_integer(StartBin),
                    parse_nonnegative_integer(EndBin)
                }
            of
                {{ok, Start}, {ok, End0}} when Start < Size, End0 >= Start ->
                    End = erlang:min(End0, Size - 1),
                    {ok, Start, End - Start + 1};
                {{ok, _Start}, {ok, _End}} ->
                    {error, unsatisfiable};
                _ ->
                    {error, invalid_range}
            end;
        _ ->
            {error, invalid_range}
    end.

parse_nonnegative_integer(<<>>) ->
    error;
parse_nonnegative_integer(Bin) when is_binary(Bin) ->
    try binary_to_integer(Bin) of
        Value when Value >= 0 -> {ok, Value};
        _ -> error
    catch
        error:badarg -> error
    end.

-spec content_type(binary()) -> binary().
content_type(<<"wikimedia-catalog.json">>) ->
    <<"application/json; charset=utf-8">>;
content_type(Name) ->
    case filename:extension(binary_to_list(Name)) of
        ".bz2" -> <<"application/x-bzip2">>;
        ".json" -> <<"application/json; charset=utf-8">>;
        ".jsonl" -> <<"application/x-ndjson; charset=utf-8">>;
        ".txt" -> <<"text/plain; charset=utf-8">>;
        _ -> <<"application/octet-stream">>
    end.

externalize(Map) when is_map(Map) ->
    maps:from_list([
        {externalize_key(Key), externalize(Value)}
     || {Key, Value} <- maps:to_list(Map)
    ]);
externalize(List) when is_list(List) ->
    [externalize(Value) || Value <- List];
externalize(Tuple) when is_tuple(Tuple) ->
    [externalize(Value) || Value <- tuple_to_list(Tuple)];
externalize(true) ->
    true;
externalize(false) ->
    false;
externalize(null) ->
    null;
externalize(undefined) ->
    null;
externalize(Atom) when is_atom(Atom) -> atom_to_binary(Atom, utf8);
externalize(Value) ->
    Value.

externalize_key(Key) when is_binary(Key) -> Key;
externalize_key(Key) when is_atom(Key) -> atom_to_binary(Key, utf8);
externalize_key(Key) when is_list(Key) -> unicode:characters_to_binary(Key);
externalize_key(Key) -> iolist_to_binary(io_lib:format("~p", [Key])).
