// Minimal libbpf loader that prints CSV snapshots each second: pid,comm,rx,tx
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <sys/resource.h>
#include <limits.h>
#include <dirent.h>

#include "proc_bw.skel.h"   // generated by bpftool gen skeleton

static volatile sig_atomic_t exiting = 0;
static void on_sigint(int signo) { exiting = 1; }

// read /proc/<pid>/comm
static void read_comm(int pid, char *buf, size_t n) {
    char path[64];
    snprintf(path, sizeof(path), "/proc/%d/comm", pid);
    FILE *f = fopen(path, "r");
    if (!f) { buf[0] = 0; return; }
    if (!fgets(buf, n, f)) { buf[0]=0; fclose(f); return; }
    size_t L = strlen(buf);
    if (L && buf[L-1]=='\n') buf[L-1]=0;
    fclose(f);
}

int main() {
    struct rlimit rlim = {RLIM_INFINITY, RLIM_INFINITY};
    setrlimit(RLIMIT_MEMLOCK, &rlim);

    libbpf_set_strict_mode(LIBBPF_STRICT_ALL);
    libbpf_set_print(NULL);

    struct proc_bw_bpf *skel = proc_bw_bpf__open();
    if (!skel) { fprintf(stderr, "open failed\n"); return 1; }

    if (proc_bw_bpf__load(skel)) {
        fprintf(stderr, "load failed\n");
        proc_bw_bpf__destroy(skel);
        return 1;
    }
    if (proc_bw_bpf__attach(skel)) {
        fprintf(stderr, "attach failed\n");
        proc_bw_bpf__destroy(skel);
        return 1;
    }

    signal(SIGINT, on_sigint);
    signal(SIGTERM, on_sigint);
    setvbuf(stdout, NULL, _IOLBF, 0); // line-buffered

    int map_rx = bpf_map__fd(skel->maps.bytes_rx);
    int map_tx = bpf_map__fd(skel->maps.bytes_tx);

    while (!exiting) {
        // Iterate keys in both maps
        __u32 key = 0, next_key;
        // We’ll collect into a temporary hash by PID
        // For simplicity, scan rx then merge tx.
        struct { __u32 pid; __u64 val; } kv;
        // Snapshot rx
        while (bpf_map_get_next_key(map_rx, &key, &next_key) == 0) {
            __u64 v = 0;
            bpf_map_lookup_elem(map_rx, &next_key, &v);
            char comm[64]={0}; read_comm((int)next_key, comm, sizeof(comm));
            // Print with tx placeholder; we will fill tx later if missing
            printf("%u,%s,%llu,%llu\n", next_key, comm, (unsigned long long)v, 0ULL);
            key = next_key;
        }
        // Snapshot tx
        key = 0;
        while (bpf_map_get_next_key(map_tx, &key, &next_key) == 0) {
            __u64 v = 0;
            bpf_map_lookup_elem(map_tx, &next_key, &v);
            // To avoid duplicate rows, print tx rows; rx=0 for new pids
            char comm[64]={0}; read_comm((int)next_key, comm, sizeof(comm));
            printf("%u,%s,%llu,%llu\n", next_key, comm, 0ULL, (unsigned long long)v);
            key = next_key;
        }
        puts("--tick--");
        usleep(1000000);
    }

    proc_bw_bpf__destroy(skel);
    return 0;
}
