* B
  - Blog
    - [[file:articles/quantum_of_verification.org::*Quantum Collaboration: The Observer Effect & DamageBDD's Pioneering Approach to Software Behaviour Verification!][IntroductioN]]
* I
  - [[file:articles/quantum_of_verification.org::*Quantum Collaboration: The Observer Effect & DamageBDD's Pioneering Approach to Software Behaviour Verification!][Introduction]]
* W
  - [[file:articles/whatisdamage.org::*What is the function of damage in the context of software engineering?][What is Damage?]]
